name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PY_COLORS: 1

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install requirements
        run: pip install -r requirements_frozen.txt
      - name: Run tests
        run: pytest
